/**
 * Названия игровых систем сервиса игр по коду.
 *
 * Справочник `GET /api/v1/game-systems` с нашего сайта недоступен: шлюз
 * сервиса пускает чужие сайты только к каталогу игр. Поэтому держим копию;
 * система, которой здесь нет, показывается своим кодом.
 */
export const HOME_GAME_SYSTEM_NAMES: Record<string, string> = {
  THIRTEENTH_AGE: '13th Age',
  SEVENTH_SEA: '7th Sea',
  ADND: 'AD&D',
  ALIEN_RPG: 'Alien RPG',
  APOCALYPSE_WORLD: 'Apocalypse World',
  AVATAR_LEGENDS: 'Avatar Legends',
  BASIC_ROLEPLAYING: 'Basic Roleplaying',
  BLADE_RUNNER: 'Blade Runner RPG',
  BLADES_IN_THE_DARK: 'Blades in the Dark',
  BURNING_WHEEL: 'Burning Wheel',
  CAIRN: 'Cairn',
  CALL_OF_CTHULHU: 'Call of Cthulhu',
  CHRONICLES_OF_DARKNESS: 'Chronicles of Darkness',
  CORIOLIS: 'Coriolis',
  CYBERPUNK_2020: 'Cyberpunk 2020',
  CYBERPUNK_RED: 'Cyberpunk RED',
  CYPHER_SYSTEM: 'Cypher System (Numenera)',
  DAGGERHEART: 'Daggerheart',
  DND_35: 'D&D 3.5',
  DND_4E: 'D&D 4',
  DND_2014: 'D&D 5 (2014)',
  DND_2024: 'D&D 5 (2024)',
  DELTA_GREEN: 'Delta Green',
  DRAGONBANE: 'Dragonbane',
  DREAD: 'Dread',
  DCC: 'Dungeon Crawl Classics',
  DUNGEON_WORLD: 'Dungeon World',
  FATE_ACCELERATED: 'Fate Accelerated',
  FATE_CORE: 'Fate Core',
  FORBIDDEN_LANDS: 'Forbidden Lands',
  GENESYS: 'Genesys',
  GURPS: 'GURPS',
  HUNTER_RECKONING: 'Hunter: The Reckoning',
  IRONSWORN: 'Ironsworn',
  STARFORGED: 'Ironsworn: Starforged',
  KIDS_ON_BIKES: 'Kids on Bikes',
  KNAVE: 'Knave',
  KULT: 'Kult: Divinity Lost',
  LANCER: 'Lancer',
  LEGEND_OF_FIVE_RINGS: 'Legend of the Five Rings',
  LEVEL_UP_A5E: 'Level Up: Advanced 5th Edition',
  MAGE_ASCENSION: 'Mage: The Ascension',
  MARVEL_MULTIVERSE: 'Marvel Multiverse RPG',
  MASKS: 'Masks: A New Generation',
  MONSTER_OF_THE_WEEK: 'Monster of the Week',
  MORK_BORG: 'Mörk Borg',
  MOTHERSHIP: 'Mothership',
  MUTANTS_MASTERMINDS: 'Mutants & Masterminds',
  MUTANT_YEAR_ZERO: 'Mutant: Year Zero',
  OSE: 'Old-School Essentials',
  PARANOIA: 'Paranoia',
  PATHFINDER_1E: 'Pathfinder 1e',
  PATHFINDER_2E: 'Pathfinder 2e',
  PENDRAGON: 'Pendragon',
  RUNEQUEST: 'RuneQuest',
  SAVAGE_WORLDS: 'Savage Worlds',
  SHADOWDARK: 'Shadowdark',
  SHADOWRUN: 'Shadowrun',
  STARFINDER: 'Starfinder',
  STAR_TREK_ADVENTURES: 'Star Trek Adventures',
  STAR_WARS_FFG: 'Star Wars (FFG)',
  SYMBAROUM: 'Symbaroum',
  TALES_OF_THE_VALIANT: 'Tales of the Valiant',
  THE_ONE_RING: 'The One Ring',
  TINY_D6: 'Tiny d6',
  TRAIL_OF_CTHULHU: 'Trail of Cthulhu',
  TRAVELLER: 'Traveller',
  TWILIGHT_2000: 'Twilight: 2000',
  VAESEN: 'Vaesen',
  VAMPIRE_MASQUERADE: 'Vampire: The Masquerade',
  WARHAMMER_40K: 'Warhammer 40,000 Roleplay',
  WFRP: 'Warhammer Fantasy Roleplay',
  WEREWOLF_APOCALYPSE: 'Werewolf: The Apocalypse',
  HOMEBREW: 'Своя система',
};
