import type { GlobalThemeOverrides } from 'naive-ui';

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    borderRadius: '8px',
    textColorBase: 'var(--text-color)',
  },
  Checkbox: {
    borderRadius: '4px',
    color: 'var(--checkbox-bg)',
    colorDisabled: 'var(--border)',
    colorChecked: 'var(--primary)',
    colorDisabledChecked: 'var(--primary-disabled)',
    textColor: 'var(--text-color)',
    textColorDisabled: 'var(--text-color-disabled)',
    border: 'var(--border)',
    borderChecked: 'var(--border)',
    borderFocus: 'var(--border)',
    borderDisabled: 'var(--border)',
    borderDisabledChecked: 'var(--border)',
    boxShadowFocus: 'var(--checkbox-shadow)',
  },
  Skeleton: {
    color: 'var(--hover)',
    colorEnd: 'var(--bg-main)',
  },
  Button: {    
    color: 'var(--primary)',
    colorHover: 'var(--primary-hover)',
    colorPressed: 'var(--primary-active)',
    colorFocus: 'var(--primary)',
    colorDisabled: 'var(--primary-disabled)',

    border: '1px solid var(--border)',
    borderHover: 'var(--primary-hover)',
    borderPressed: 'var(--primary-active)',
    borderFocus: 'var(--primary)',
    borderDisabled: 'var(--primary-disabled)',

    colorPrimary: 'var(--primary)',
    colorHoverPrimary: 'var(--primary-hover)',
    colorPressedPrimary: 'var(--primary-active)',
    colorFocusPrimary: 'var(--primary)',
    colorDisabledPrimary: 'var(--primary-disabled)',
    borderPrimary: 'var(--primary)',
    borderHoverPrimary: 'var(--primary-hover)',
    borderPressedPrimary: 'var(--primary-active)',
    borderFocusPrimary: 'var(--primary)',
    borderDisabledPrimary: 'var(--primary-disabled)',
    textColorPrimary: 'var(--text-btn-color)',
    textColorHoverPrimary: 'var(--text-btn-color)',
    textColorPressedPrimary: 'var(--text-btn-color)',
    textColorFocusPrimary: 'var(--text-btn-color)',
    textColorDisabledPrimary: 'var(--text-btn-color)',

    colorSecondary: 'rgba(255, 255, 255, .01)',
    colorHoverSecondary: 'var(--hover)',
    colorPressedSecondary: 'var(--primary-active)',
    colorFocusSecondary: 'var(--primary)',
    colorDisabledSecondary: 'var(--primary-disabled)',
    
    textColor: 'var(--text-btn-color)',
    textColorHover: 'var(--text-btn-color)',
    textColorTertiary: 'var(--text-btn-color)',
    textColorPressed: 'var(--text-btn-color)',
    textColorFocus: 'var(--text-btn-color)',
    textColorDisabled: 'var(--text-btn-color)',
  },
};
