name: Build

on:
  workflow_call:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: TTG-Club/ttg-club-frontend
          ref: ${{ github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:${{ github.ref_name == 'dev' && 'dev' || 'prod' }}

      - uses: actions/upload-artifact@v4
        with:
          name: front-build-${{ github.run_id }}
          path: ./
          retention-days: 1
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: front-app-${{ github.run_id }}
          path: ./dist
          retention-days: 1
          if-no-files-found: error
