name: Code Check

on:
  workflow_call:

permissions:
  security-events: write

concurrency:
  group: code-check-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check:
    name: Build and Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: TTG-Club/ttg-club-frontend
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --cache .npm

      - name: Build
        run: npm run build:prod

      - name: ESLint
        run: npm run lint:workflow

      - name: Stylelint
        run: npm run stylelint:workflow
