name: Deploy TTG Club Frontend

on:
  push:
    branches:
      - main
      - dev

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: deploy-frontend-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  deploy-dev:
    name: Deploy Develop
    if: ${{ github.ref_name == 'dev' }}
    needs: lint
    uses: ttg-club/ttg-club-backend/.github/workflows/docker-deploy.yml@dev

  deploy-prod:
    name: Deploy Production
    if: ${{ github.ref_name == 'main' }}
    needs: lint
    uses: ttg-club/ttg-club-backend/.github/workflows/docker-deploy.yml@main
