name: Deploy TTG Club Frontend

on:
  push:
    branches:
      - main
      - dev

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}-${{ github.action }}-${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  deploy:
    name: Deploy
    needs: lint
    uses: ${{ github.repository_owner }}/ttg-club-backend/.github/workflows/docker-deploy.yml@${{ github.ref_name }}
