name: Deploy

on:
  push:
    branches:
      - main
      - dev

permissions:
  actions: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  dispatch-deploy:
    name: Dispatch Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |-
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'ttg-club-backend',
              workflow_id: 'docker-deploy.yml',
              ref: "${{ github.ref_name }}"
            })
