name: Deploy TTG Club Frontend

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref }}-${{ github.action }}-${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  deploy:
    name: Deploy
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |-
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'ttg-club-backend',
              workflow_id: 'docker-deploy.yml',
              ref: "${{ github.ref_name }}"
            })
