name: Lint

on:
  workflow_call:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: lint-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: front-build-${{ github.run_id }}

      - name: ESLint
        run: npm run lint:workflow

      - name: Prettier
        run: npm run prettier:workflow
