name: Pull Request Lint

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

    branches:
      - main
      - dev

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: lint-pr-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: Lint PR
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/lint.yml

  type-check-pr:
    name: Type check PR
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/lint.yml
