name: Lint

on:
  workflow_call:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: lint-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --cache .npm

      - name: ESLint
        run: npm run lint:workflow

      - name: Prettier
        run: npm run prettier:workflow

      - name: Stylelint
        run: npm run stylelint:workflow
