name: Lint TTG Club Frontend

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - unlocked
      - review_requested

    branches:
      - main
      - dev

  workflow_dispatch:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: ${{ github.ref }}-${{ github.action }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint application
        run: npm run lint:fix
