name: Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - unlocked
      - review_requested

    branches:
      - main
      - dev

  workflow_call:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: lint-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: TTG-Club/ttg-club-frontend
          ref: ${{ github.ref_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v3
        env:
          cache-name: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Lint application
        run: npm run lint:fix
