name: Type check

on:
  workflow_call:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: type-check-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - uses: actions/download-artifact@v3
        with:
          name: front-build-${{ github.run_id }}

      - name: Type-check application
        run: npm run type-check
